import React from 'react';

export default class Main extends React.Component {
    render() {
        return (
            <div>
                <h1>Lorem Ipsum</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae congue eu consequat ac felis donec et odio. Condimentum lacinia quis vel eros donec ac odio. Consequat ac felis donec et odio pellentesque. Imperdiet nulla malesuada pellentesque elit. Justo nec ultrices dui sapien eget mi proin sed. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Sed odio morbi quis commodo odio aenean sed adipiscing. Elementum eu facilisis sed odio morbi quis commodo odio. Ut aliquam purus sit amet luctus venenatis. Commodo sed egestas egestas fringilla phasellus faucibus. Auctor urna nunc id cursus metus aliquam eleifend. Odio pellentesque diam volutpat commodo. Feugiat nisl pretium fusce id velit ut. Eu scelerisque felis imperdiet proin fermentum.</p>
                <p>Quisque non tellus orci ac auctor augue mauris augue. Donec massa sapien faucibus et. Sem nulla pharetra diam sit. Cras pulvinar mattis nunc sed. Sit amet nulla facilisi morbi tempus iaculis urna id. Pharetra convallis posuere morbi leo urna. Volutpat maecenas volutpat blandit aliquam etiam erat velit. Pulvinar etiam non quam lacus. Egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam. Quam adipiscing vitae proin sagittis nisl. Suspendisse potenti nullam ac tortor. Elementum nibh tellus molestie nunc non blandit. Quis viverra nibh cras pulvinar mattis nunc sed blandit libero. Tortor id aliquet lectus proin nibh nisl.</p>
                <p>Quisque id diam vel quam elementum pulvinar. Aenean euismod elementum nisi quis eleifend quam adipiscing vitae. Senectus et netus et malesuada fames. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Congue quisque egestas diam in arcu cursus euismod quis viverra. A pellentesque sit amet porttitor eget. Diam maecenas sed enim ut sem viverra aliquet eget. Varius vel pharetra vel turpis nunc eget lorem dolor sed. Egestas purus viverra accumsan in. Euismod quis viverra nibh cras pulvinar. Cursus mattis molestie a iaculis at. Hendrerit gravida rutrum quisque non tellus orci ac.</p>
                <p>Sit amet volutpat consequat mauris nunc congue. Quisque sagittis purus sit amet volutpat. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Nulla porttitor massa id neque aliquam vestibulum. Ac tortor dignissim convallis aenean et tortor at. Morbi non arcu risus quis varius quam. Sed nisi lacus sed viverra tellus in. Fames ac turpis egestas maecenas pharetra convallis posuere morbi. Dictum non consectetur a erat nam. Ac ut consequat semper viverra.</p>
                <p>Sollicitudin ac orci phasellus egestas tellus rutrum. Facilisi cras fermentum odio eu feugiat pretium nibh. Amet cursus sit amet dictum sit amet justo donec. Sit amet commodo nulla facilisi nullam. Tincidunt ornare massa eget egestas purus viverra accumsan. Et malesuada fames ac turpis. Dolor morbi non arcu risus quis. Praesent tristique magna sit amet purus gravida. Auctor elit sed vulputate mi sit amet mauris commodo. Mauris sit amet massa vitae tortor condimentum lacinia. Lacus sed viverra tellus in hac habitasse platea dictumst. Consectetur adipiscing elit ut aliquam. Facilisi nullam vehicula ipsum a arcu. Netus et malesuada fames ac. Urna duis convallis convallis tellus.</p>
            </div>
        );
    }
}